---
  - set_fact:
      traefik_config: '{{ default_traefik_config | combine(traefik_config, recursive=True) }}'

  - name: ':: config :: Ensure conf directory exsists'
    file:
      path: '{{ traefik_binary_path}}/conf'
      state: directory

  - name: ':: config :: Apply Configuration'
    template:
      src: config.j2
      dest: '{{ traefik_binary_path }}/conf/conf.toml'

  - name: ':: config :: Apply rules'
    template:
      src: '{{ traefik_config.file_backend.template }}'
      dest: '{{ traefik_binary_path }}/conf/{{ traefik_config.file_backend.filename}}'
    when: '{{ traefik_config.file_backend }}'
